### ISSUE TITLE
bug when work with cmdline-window (aka `q:`)

### ISSUE THREAD

**Issue by milanglacier** [Saghen/blink.cmp#583] opened 2024-12-16 08:37 UTC
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

I got this error when start to type anything in cmdline window (aka the window popped up by `q:`).

The error traceback is 

```lua
rror executing vim.schedule lua callback: ...azy/blink.cmp/lua/blink/cmp/lib/window/scrollbar/win.lua:73: E11: Invalid in command-line window; <CR> executes, C
TRL-C quits                                                                                                                                                     
stack traceback:                                                                                                                                                
        [C]: in function 'nvim_buf_delete'                                                                                                                      
        ...azy/blink.cmp/lua/blink/cmp/lib/window/scrollbar/win.lua:73: in function 'update'                                                                    
        ...re/nvim/lazy/blink.cmp/lua/blink/cmp/lib/window/init.lua:126: in function 'close'                                                                    
        ...lazy/blink.cmp/lua/blink/cmp/completion/windows/menu.lua:78: in function 'close'                                                                     
        ...re/nvim/lazy/blink.cmp/lua/blink/cmp/completion/init.lua:44: in function 'callback'                                                                  
        .../nvim/lazy/blink.cmp/lua/blink/cmp/lib/event_emitter.lua:28: in function 'emit'                                                                      
        ...re/nvim/lazy/blink.cmp/lua/blink/cmp/completion/list.lua:118: in function 'hide'                                                                     
        ...re/nvim/lazy/blink.cmp/lua/blink/cmp/completion/init.lua:23: in function 'callback'                                                                  
        .../nvim/lazy/blink.cmp/lua/blink/cmp/lib/event_emitter.lua:28: in function 'emit'                                                                      
        ...lazy/blink.cmp/lua/blink/cmp/completion/trigger/init.lua:202: in function 'hide'                                                                     
        .../.local/share/nvim/lazy/blink.cmp/lua/blink/cmp/init.lua:52: in function <.../.local/share/nvim/lazy/blink.cmp/lua/blink/cmp/init.lua:50>   
```

### Relevant configuration

```lua
No configuration is needed,

`require 'blink-cmp'.setup {}` is sufficient to reproduce the problem
```

### neovim version

0.10.2

### `blink.cmp` version: branch, tag, or commit

12ffc10c6283ac148a89d72b5540d819fc80e2ff

**Comment by Saghen** [comment] 2024-12-16 16:09
Duplicate of #580

**Closed by Saghen** 2024-12-16 16:09 UTC
Labels: bug
