### ISSUE TITLE
Auto-completion triggered without typing anything in telescope (fuzzy find) window. This started happening on v0.8.0 and believe its related to cmdline completions.

### ISSUE THREAD

**Issue by Or1g3n** [Saghen/blink.cmp#802] opened 2024-12-27 17:39 UTC
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

Ever since v0.8.0 which introduced cmdline completions (which I am very thankful for btw) the autocomplete menu is randomly triggered upon opening telescope (fuzzy find) windows even though nothing has been typed. In addition, the autocomplete options shown are nonsensical and quite random.

 
![image](https://github.com/user-attachments/assets/5ef8e199-2d02-4cb5-91af-5fc999043f56)

### neovim version

NVIM v0.11.0-dev

### `blink.cmp` version: branch, tag, or commit

v0.8.2

**Comment by axburgess-godaddy** [comment] 2024-12-27 18:44
```
    completion = {  
      menu = {
        auto_show = function()
          return vim.bo.buftype ~= "prompt" and vim.b.completion ~= false and vim.bo.filetype ~= "TelescopePrompt"
        end,
      },
```
is working for me

**Comment by Muizzyranking** [comment] 2024-12-28 06:16
```lua
{
  "saghen/blink.cmp",
  opts = {
    enabled = function()
      -- you list filetypes where you don't want blink blink to work here
      local disabled_filetypes = { "TelescopePrompt" }
      return not vim.tbl_contains(disabled_filetypes, vim.bo.filetype) and vim.b.completion ~= false
    end,
  },
}
```

This should solve the issues.

If you are getting completions where you don't want, get the fileype, then add it to the list.

**Comment by Or1g3n** [comment] 2024-12-28 16:37
I appreciate your guidance. I am aware of the ability to disable auto-complete for certain buffer types. I just want to make sure this isn't masking an inherent bug that is present in v.0.8.0+. The issue is not that I want to disable auto-complete in a TelescopePrompt buffer, the issue is that when a TelescopePrompt buffer opens, an auto-complete menu with non-nonsensical completion options opens up even though I have not typed anything. If I do type something the menu remains static and options for auto-complete do not change; I have to press escape to get it to disappear. So while simply disabling blink.cmp for Telescope buffers would work this does not address the strange behavior which was not present in past versions.

**Comment by Saghen** [comment] 2024-12-29 00:10
Duplicate of #730

**Comment by Saghen** [comment] 2024-12-29 00:11
Duplicate of #716

**Closed by Saghen** 2024-12-29 00:10 UTC
Labels: bug
