### ISSUE TITLE
enable friendly_snippets let lsp complete broken

### ISSUE THREAD

**Issue by fcying** [Saghen/blink.cmp#72] opened 2024-10-09 23:37 UTC
test commit  88f71b1

friendly_snippets  false
![image](https://github.com/user-attachments/assets/b5fe0583-a184-4cae-931b-79994e68bb8e)

friendly_snippets  true
can't see lsp source
![image](https://github.com/user-attachments/assets/01258841-b1be-460f-92ed-28e7e2d674eb)

config
```
        sources = {
            providers = {
                {
                    { "blink.cmp.sources.lsp" },
                    { "blink.cmp.sources.path" },
                    {
                        "blink.cmp.sources.snippets",
                        score_offset = -3,
                        opts = {
                            friendly_snippets = false,
                            global_snippets = { "all" },
                            extended_filetypes = {},
                            ignored_filetypes = {},
                        },
                    },
                },
                { { "blink.cmp.sources.buffer" } },
            },
        },
```

**Comment by lopi-py** [comment] 2024-10-12 06:11
Duplicate of #67

**Closed** 2024-10-12 06:12 UTC
