### ISSUE TITLE
Keymap for Esc sends cmdline command for fallback

### ISSUE THREAD

**Issue by elliotwesoff** [Saghen/blink.cmp#752] opened 2024-12-24 07:57 UTC
### Bug Description

When a keymap is set for `<Esc>` and escape is pressed when typing in the cmdline, the command is always sent. For example:

* From normal mode, type `:w`
* Press escape
* Notice that nvim writes the file

nvim does not write to the file when the `<Esc>` keymap is not set, which is the expected behavior.

### Relevant configuration

```lua
keymap = {
      preset = 'none',
      ['<C-space>'] = { 'show', 'show_documentation', 'hide_documentation' },
      ['<Tab>'] = { 'select_next', 'fallback' },
      ['<S-Tab>'] = { 'select_prev', 'fallback' },
      ['<Up>'] = { 'scroll_documentation_up', 'fallback' },
      ['<Down>'] = { 'scroll_documentation_down', 'fallback' },
      ['<CR>'] = { 'accept', 'fallback' },
      ['<Esc>'] = { 'hide', 'fallback' }
    }
```

### neovim version

v0.10.2

### `blink.cmp` version: branch, tag, or commit

v0.8.2

**Comment by Saghen** [comment] 2024-12-24 16:40
Duplicate of #547

**Closed by Saghen** 2024-12-24 16:40 UTC
Labels: bug
