### ISSUE TITLE
Manual completion (aka `cmp.show()`) should always show regardless of the `min_keyword_length`

### ISSUE THREAD

**Issue by milanglacier** [Saghen/blink.cmp#647] opened 2024-12-19 01:07 UTC
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

This is a continuation of a scenario described in https://github.com/Saghen/blink.cmp/issues/582#issuecomment-2544965222,

> I think when the user want to invoke the completion manually via a keybinding, then it makes sense to show the completion popup immediately, regardless of min_keyword_length

Currently something like `function(cmp) cmp.show { providers = { 'minuet' } } end` will not be triggered if `min_keyword_length` is not 0.

### neovim version

0.10

### `blink.cmp` version: branch, tag, or commit

HEAD

**Comment by Saghen** [comment] 2024-12-19 04:05
Duplicate of #643

**Closed by Saghen** 2024-12-19 04:05 UTC
Labels: bug
