### ISSUE TITLE
bug: attempt to call field 'fuzzy_matched_indices' (a nil value)

### ISSUE THREAD

**Issue by adelarsq** [Saghen/blink.cmp#375] opened 2024-11-24 23:08 UTC
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

First, thanks for the huge effort on this amazing plugin. Has been a great companion for me.

For some reason after the 0.6.0 and 0.6.1 update I am getting this error:

```
Error  19:58:20 msg_show.lua_error Error executing vim.schedule lua callback: ...l/share/nvim/lazy/blink.cmp/lua/blink/cmp/fuzzy/init.lua:24: attempt to call field 'fuzzy_matched_indices' (a nil value)
stack traceback:
	...l/share/nvim/lazy/blink.cmp/lua/blink/cmp/fuzzy/init.lua:24: in function 'fuzzy_matched_indices'
	.../lazy/blink.cmp/lua/blink/cmp/windows/render/context.lua:21: in function 'get_from_items'
	...vim/lazy/blink.cmp/lua/blink/cmp/windows/render/init.lua:54: in function 'draw'
	...im/lazy/blink.cmp/lua/blink/cmp/windows/autocomplete.lua:111: in function 'open_with_items'
	.../.local/share/nvim/lazy/blink.cmp/lua/blink/cmp/init.lua:57: in function <.../.local/share/nvim/lazy/blink.cmp/lua/blink/cmp/init.lua:51>                  
```

Version 0.5.1 is working fine. I using it for now, but I can help to test this issue.

I am using on OSX 10.15.7.

### Relevant configuration

```lua
{
        'https://github.com/saghen/blink.cmp',
        lazy = false,
        dependencies = 'https://github.com/rafamadriz/friendly-snippets',
        version = 'v0.*',
        ---@module 'blink.cmp'
        ---@type blink.cmp.Config
        opts = {
            keymap = {
                ["<D-c>"] = { "show" },
                ["<S-CR>"] = { "hide" },
                ["<CR>"] = { "select_and_accept", "fallback" },
                ["<Tab>"] = { "select_next", "fallback" },
                ["<S-Tab>"] = { "select_prev", "fallback" },
                ["<Down>"] = { "select_next" },
                ["<Up>"] = { "select_prev" },
                ["<PageDown>"] = { "scroll_documentation_down" },
                ["<PageUp>"] = { "scroll_documentation_up" },
            },
            highlight = {
                use_nvim_cmp_as_default = true,
            },
            nerd_font_variant = 'normal',
            windows = {
                ghost_text = {
                    enabled = true,
                },
            },
            sources = {
                completion = {
                    enabled_providers = { "lsp", "path", "snippets", "buffer", "dadbod" },
                },
                providers = {
                    dadbod = { name = "Dadbod", module = "vim_dadbod_completion.blink" },
                },
            },
        },
    },
```

### neovim version

NVIM v0.11.0-dev-1220+gd9b08c58c3

### `blink.cmp` version: branch, tag, or commit

v0.6.1

**Comment by Saghen** [comment] 2024-11-24 23:11
Hey there, it seems likely the downloader failed to get the new prebuilt binary, something I've been tracking in #68 but have had trouble reproducing... Does reinstalling the plugin solve the issue for you?

**Comment by adelarsq** [comment] 2024-11-24 23:18
@Saghen I will try. But I have confirmed that the download is failing. It's getting another binary than [x86_64-apple-darwin.dylib](https://github.com/Saghen/blink.cmp/releases/download/v0.6.1/x86_64-apple-darwin.dylib). Doing manual download and rename works fine.

**Comment by adelarsq** [comment] 2024-11-24 23:22
@Saghen Confirmed. A fresh install also works. I will stick with 0.6.1 and see what happens.

**Comment by Saghen** [comment] 2024-11-24 23:23
Great thanks! Marking this as duplicate of #68

**Closed by Saghen** 2024-11-24 23:23 UTC
Labels: bug

**Comment by jasmine-nguyen** [comment] 2024-11-25 01:13
Thanks @Saghen , confirmed a fresh install fixed it.
