### ISSUE TITLE
UX: update the existing completion window instead of closing and re-opening

### ISSUE THREAD

**Issue by s1n7ax** [Saghen/blink.cmp#750] opened 2024-12-24 06:41 UTC
### Feature Description

Following is the slow down version of completion I see with JDTLS (jdtls is slower compared to other LS). I see a lot of screen flicker. I think if we can detect the existing window and update it without reopening it, we would have better user experience.

https://github.com/user-attachments/assets/78d38c65-a8a1-4d05-a16a-41e56ed9ce41

**Comment by Saghen** [comment] 2024-12-24 16:26
Duplicate of #691

Also, if you could run `:lua vim.print(vim.lsp.get_clients({ bufnr = 0, method = 'textDocument/completion' }))` and send the output, that would be very helpful

**Closed** 2024-12-24 16:27 UTC
Labels: feature
