### ISSUE TITLE
Neovim crash on autocomplete suggestion initiation

### ISSUE THREAD

**Issue by ArykLAnderson** [Saghen/blink.cmp#754] opened 2024-12-24 09:11 UTC
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

I was running into an issue where whenever blink autocomplete would start, the entire neovim program would crash. This persisted through uninstalling and reinstalling neovim, and stripping down neovim plugins to only the stock plugins (now containing blink) from the LazyVim distribution that I use. That distribution is set to lazy load blink on insert enter, and when I would start typing characters I was able to type 1-3 characters before the program would crash.

I was able to recover by finding and deleting both the blink mongodb files and all the files in the lazy install path, then re-installing everything.

Unfortunately I'm not sure how to reproduce this state, and the crashes produced no error logs, but hopefully this can at minimum be a data point for a future resolution. Thanks for your work on this!

### neovim version

NVIM v0.10.3 Build type: Release LuaJIT 2.1.1734355927

### `blink.cmp` version: branch, tag, or commit

v0.8.2

**Comment by guigui64** [comment] 2024-12-24 09:40
I have the same issue and reproduced with versions 0.8.1 and 0.8.0.
This could mean that the state files are compromised.

**Comment by konart** [comment] 2024-12-24 12:14
Same here, but deleting `.local/share/nvim/blink` did nothing for me.

**Comment by Saghen** [comment] 2024-12-24 16:23
Duplicate of #68 

If someone could share a zip of their `.local/share/nvim/lazy/blink.cmp` while it's broken, that would be super helpful btw

**Closed by Saghen** 2024-12-24 16:23 UTC
Labels: bug

**Comment by surmish** [comment] 2024-12-24 19:39
In most cases, running `ldd libblink_cmp_fuzzy.so` would show any errors, which lead to the crash on autocomplete initiation. In my case, the `gblic` on my machine was not compatible with the binary downloaded. Compiling it manually worked out (see https://github.com/Saghen/blink.cmp/issues/68#issuecomment-2560312574).
