### ISSUE TITLE
Trigger character written twice on completion

### ISSUE THREAD

**Issue by mtarld** [Saghen/blink.cmp#293] opened 2024-11-08 09:55 UTC
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

In a PHP file with LSP enabled, blink doesn't complete variables in a way I expect to.

Let's say we have the following file:
```php
$classMetadataFactory = new ClassMetadataFactory(new AnnotationLoader());
```

If I put my cursor after the last line, type `$cl`, and accept the completion, this results in:
```php
$classMetadataFactory = new ClassMetadataFactory(new AnnotationLoader());
$$classMetadataFactory
```

Of course, I don't expect having two `$`. My guess is that the trigger character is not ignored, and therefore inserted a second time.

I digged a little and have created a fix on my local version. I updated `lua/blink/cmp/accept/init.lua` with the following:
```diff
local function accept(item)
  require('blink.cmp.trigger.completion').hide()

  require('blink.cmp.sources.lib')
    .resolve(item)
    :map(function(resolved_item)
      -- ...

      -- Add brackets to the text edit if needed
      local brackets_status, text_edit_with_brackets, offset = brackets_lib.add_brackets(vim.bo.filetype, item)
      item.textEdit = text_edit_with_brackets
+
+      -- Move on char left if the first char is a trigger character
+      if (vim.tbl_contains(sources.get_trigger_characters(), string.sub(item.textEdit.newText, 1, 1))) then
+        item.textEdit.range.start.character = item.textEdit.range.start.character - 1
+      end

      -- Snippet
      -- ...
```
But I'm not sure this is the way to go. And I'd love helping you on that subject, I can open a PR if needed.

Thanks for that great project btw :slightly_smiling_face: 

### neovim version

v0.10.2

### `blink.cmp` version: branch, tag, or commit

v0.5.1

**Comment by Saghen** [comment] 2024-11-09 01:23
Thanks for the kind words :) This seems to be a duplicate of #46. If the LSP doesn't return edit ranges, and the text to be inserted includes characters not in the keyword_regex, you'll end up with exactly this situation. The solution should be more general than including the trigger character (i.e. this wouldn't solve the case from #46). You can double check if your LSP is returning edit ranges by putting a `vim.print(resolved_item)` in `lua/accept/init.lua`

**Closed by Saghen** 2024-11-09 01:23 UTC
Labels: bug

**Comment by Saghen** [comment] 2024-11-11 00:55
It's possible that https://github.com/Saghen/blink.cmp/commit/db3d1ad8d6420ce29d548991468cc0107fe9d04b solves this, assuming the PHP language server returns edit ranges via item defaults

**Comment by HalibutGitWiz** [comment] 2024-12-24 15:45
Same on v0.8.2 with phpactor

I recently migrated from nvim-cmp to blink, with the same language server, and never had this problem before. So I don't think that's a language server issue, or at least there must be a workaround.

I checked in closed issues on nvim-cmp repo to see if they encountered this at some point and solved it, but found nothing. :disappointed:

**Comment by DaanHoogendoorn** [comment] 2024-12-24 17:04
With phpactor you can get around this by adding `['language_server_completion.trim_leading_dollar'] = true` to the `init_options`.

Example from my config:
```lua
      phpactor = {
        filetypes = { 'php', 'blade', 'php_only' },
        init_options = {
          ['language_server_worse_reflection.inlay_hints.enable'] = true,
          ['language_server_worse_reflection.inlay_hints.params'] = true,
          ['language_server_worse_reflection.inlay_hints.types'] = true,
          ['language_server_completion.trim_leading_dollar'] = true,
        },
      },
```

**Comment by HalibutGitWiz** [comment] 2024-12-25 11:59
Solved it for me, thank you very much. :+1:
