### ISSUE TITLE
FR: Include import source

### ISSUE THREAD

**Issue by dan-woz** [Saghen/blink.cmp#177] opened 2024-10-23 21:29 UTC
When there are multiple import tokens with the same name, it's difficult to tell which token should actually be selected to get the correct automatic import.

### blink.cmp

<img width="235" alt="image" src="https://github.com/user-attachments/assets/1ba39548-8a89-41c1-a42d-6cc21525664b">

### nvim-cmp

<img width="692" alt="image" src="https://github.com/user-attachments/assets/79a9548d-f917-472d-a92b-21b6765928af">

---

In the example above, I want to select and import the `typing` module, not the `pydantic.typing` module. Ignoring the difference in available options (pyright sucks), you can see that nvim-cmp includes source information.

**Comment by Saghen** [comment] 2024-10-23 23:43
Duplicate of #127

**Closed by Saghen** 2024-10-23 23:43 UTC
