### ISSUE TITLE
Path completion doesn't show on `./foo.|`

### ISSUE THREAD

**Issue by the-fuckin-nobody** [Saghen/blink.cmp#761] opened 2024-12-24 20:11 UTC
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

I have two issues regarding this. So, first of all,  the path completion auto-hides on typing the `.` character, while trying to complete a filename with an extension.

And second, after adding `.`, blink also forgets the previous context. 

For example: 
Suppose I'm trying to complete the path `~/.config/nvim/init.lua`
completion works file till I type `~/.config/nvim/init`. But as soon as I type the `.` character, the completion menu hides and also blink forgets about the file name and starts suggesting things with a fresh(no?) context ( On typing `l` it should suggest the whole filename i.e `init.lua` but it doesn't. ) 

Also, Merry Christmas.

### Relevant configuration

```lua
local Plugin = {
	"Saghen/blink.cmp",
	cond = true,
	event = { "InsertEnter", "CmdLineEnter" },
	build = "cargo build --release",
}

Plugin.dependencies = {
	"rafamadriz/friendly-snippets",
	{
		"L3MON4D3/LuaSnip",
		version = "v2.3.0",
		build = "make install_jsregexp",
		opts = function()
			local types = require("luasnip.util.types")
			vim.keymap.set({ "i", "s" }, "<Tab>", function()
				if require("luasnip").expandable() then
					vim.notify("expandable")
					require("luasnip").expand()
				end
				vim.notify("no_expandable")
			end)
			return {
				history = true,
				update_events = { "TextChanged", "TextChangedI" },
				enable_autosnippets = true,
				ext_opts = {
					[types.choiceNode] = {
						active = {
							virt_text = { { "<- ", "Error" } },
						},
					},
				},
			}
		end,
	},
	"echasnovski/mini.icons",
	-- { "Saghen/blink.compat", opts = { impersonate_nvim_cmp = true } },
}

Plugin.config = function()
	local cmp = require("blink.cmp")
	local luasnip = require("luasnip")
	cmp.setup({
		enabled = function()
			return vim.tbl_contains({ "nofile", "prompt" }, vim.bo.buftype) == false
		end,
		keymap = {
			preset = nil,
			["<m-k>"] = { "select_prev", "fallback" },
			["<m-j>"] = { "select_next", "fallback" },
			["<m-l>"] = {
				function()
					if cmp.snippet_active() then
						return cmp.snippet_forward()
					end
					return cmp.select_and_accept()
				end,
				"fallback",
			},
			["<m-h>"] = {
				"snippet_backward",
				"fallback",
			},
			["<m-f>"] = { "scroll_documentation_down", "fallback" },
			["<m-b>"] = { "scroll_documentation_up", "fallback" },
			["<m-c>"] = { "show", "cancel", "fallback" },
			cmdline = {
				["<Tab>"] = { "select_next" },
				["<m-j>"] = { "select_next" },
				["<S-Tab>"] = { "select_prev" },
				["<m-k>"] = { "select_prev" },
			},
		},
		snippets = {
			expand = function(snippet)
				luasnip.lsp_expand(snippet)
			end,
			active = function(filter)
				if filter and filter.direction then
					return luasnip.expandable() or luasnip.jumpable(filter.direction)
				end
				return luasnip.in_snippet()
			end,
			jump = function(direction)
				if luasnip.jumpable(direction) then
					luasnip.jump(direction)
				end
			end,
		},
		completion = {
			keyword = {
				range = "full",
				regex = "[-_]\\|\\k",
				exclude_from_prefix_regex = "[\\-]",
			},
			trigger = {
				show_in_snippet = true,
				prefetch_on_insert = false,
				show_on_keyword = true,
				show_on_trigger_character = true,
				show_on_accept_on_trigger_character = true,
				show_on_insert_on_trigger_character = true,
				show_on_blocked_trigger_characters = {},
				show_on_x_blocked_trigger_characters = { "(", "'", '"' },
			},
			list = {
				max_items = 200,
				selection = function(ctx)
                    if ctx.mode == 'cmdline' then
                        return 'auto_insert'
                    end
                    return 'preselect'
                end,
				cycle = {
					from_bottom = true,
					from_top = true,
				},
			},
			accept = {
				create_undo_point = true,
				auto_brackets = {
					enabled = vim.bo.buftype ~= "prompt",
					default_brackets = { "(", ")", "{", "}" },
					override_brackets_for_filetypes = {},
					kind_resolution = {
						enabled = true,
						blocked_filetypes = { ".txt" },
					},
					semantic_token_resolution = {
						enabled = false,
						blocked_filetypes = {},
						timeout_ms = 400,
					},
					blocked_filetypes = { ".txt" },
					force_allow_filetypes = {},
				},
			},
			menu = {
				cmdline_position = function()
					if vim.g.ui_cmdline_pos ~= nil then
						local pos = vim.g.ui_cmdline_pos -- (1, 0)-indexed
						return { pos[1] - 1, pos[2] }
					end
					local height = (vim.o.cmdheight == 0) and 1 or vim.o.cmdheight
					return { vim.o.lines - height, 0 }
				end,
				enabled = true,
				min_width = 15,
				max_height = 10,
				border = "none",
				winblend = 0,
				winhighlight = "Normal:BlinkCmpMenu,FloatBorder:BlinkCmpMenuBorder,CursorLine:BlinkCmpMenuSelection,Search:None",
				scrollbar = true,
				scrolloff = 2,
				direction_priority = { "s", "n" },
				auto_show = true,
				draw = {
                    align_to = 'cursor',
					padding = 1,
					gap = 1,
					treesitter = { "lsp" },
					columns = {
						{ "kind_icon" },
						{ "label", "label_description", gap = 1 },
						{ "kind" },
					},
					components = {
						kind_icon = {
							ellipsis = false,
							text = function(ctx)
								-- local kind = ctx.kind
								-- local kind_icon, _, _ = require("mini.icons").get("lsp", kind)
								-- return kind_icon
                                ctx.icon_gap = ' '
								return ctx.kind_icon .. ctx.icon_gap
							end,
							highlight = function(ctx)
								return (
									require("blink.cmp.completion.windows.render.tailwind").get_hl(ctx)
									or "BlinkCmpKind"
								) .. ctx.kind
								-- local _, hl, _ = require('mini.icons').get('lsp', ctx.kind)
								-- return hl
							end,
						},
						kind = {
							ellipsis = false,
							width = { fill = true },
							text = function(ctx)
								return "<" .. ctx.kind .. ">"
							end,
							highlight = function(ctx)
								return (
									require("blink.cmp.completion.windows.render.tailwind").get_hl(ctx)
									or "BlinkCmpKind"
								) .. ctx.kind
							end,
						},
						label = {
							ellipsis = true,
							width = { fill = true, max = 50 },
							text = function(ctx)
								return ctx.label .. ctx.label_detail
							end,
							highlight = function(ctx)
								local highlights = {
									{
										0,
										#ctx.label,
										group = ctx.deprecated and "BlinkCmpLabelDeprecated" or "BlinkCmpLabel",
									},
								}
								if ctx.label_detail then
									table.insert(
										highlights,
										{ #ctx.label, #ctx.label + #ctx.label_detail, group = "BlinkCmpLabelDetail" }
									)
								end
								for _, idx in ipairs(ctx.label_matched_indices) do
									table.insert(highlights, { idx, idx + 1, group = "BlinkCmpLabelMatch" })
								end
								return highlights
							end,
						},
						label_description = {
							ellipsis = true,
							width = { max = 30 },
							text = function(ctx)
								return ctx.label_description
							end,
							highlight = "BlinkCmpLabelDescription",
						},
					},
				},
				order = {
					n = "bottom_up",
					s = "top_down",
				},
			},
			documentation = {
				auto_show = true,
				auto_show_delay_ms = 400,
				treesitter_highlighting = true,
				update_delay_ms = 100,
				window = {
					min_width = 20,
					max_width = 75,
					max_height = 15,
					border = 'padded',
					winblend = 0,
					winhighlight = "Normal:BlinkCmpDoc,FloatBorder:BlinkCmpDocBorder,CursorLine:BlinkCmpDocCursorLine,Search:None",
					scrollbar = false,
					direction_priority = {
						menu_north = { "e", "w", "n", "s" },
						menu_south = { "e", "w", "s", "n" },
					},
					desired_min_height = 5,
					desired_min_width = 20,
				},
			},
			ghost_text = {
				enabled = true,
			},
		},
		signature = {
			enabled = false,
			trigger = {
				blocked_retrigger_characters = {},
				blocked_trigger_characters = {},
				show_on_insert_on_trigger_character = true,
			},
			window = {
				min_width = 5,
				max_width = 100,
				max_height = 10,
				border = "single",
				winblend = 0,
				winhighlight = "Normal:BlinkCmpSignatureHelp,FloatBorder:BlinkCmpSignatureHelpBorder",
				scrollbar = false,
				direction_priority = { "n", "s" },
				treesitter_highlighting = true,
			},
		},
		fuzzy = {
			use_typo_resistance = false,
			use_frecency = true,
			use_proximity = true,
			-- max_items = 100,
			sorts = { "score", "label", "kind" },
			prebuilt_binaries = {
				download = true,
			},
		},
		sources = {
			transform_items = function(_, items)
				return items
			end,
			min_keyword_length = 0,
			cmdline = function()
				local type = vim.fn.getcmdtype()
				if type == "/" or type == "?" then
					return { "buffer" }
				elseif type == ":" then
					return { "cmdline", "path" }
				end
				return {}
			end,
			default = function()
				local _, node = pcall(vim.treesitter.get_node)
				return {
					"lsp",
					"path",
					"snippets",
					"luasnip",
                    "buffer"
				}
			end,
			per_filetype = {},
			providers = {
				lsp = {
					async = true,
					name = "Lsp",
					module = "blink.cmp.sources.lsp",
					enabled = true,
					score_offset = 0,
					fallbacks = { "buffer" },
				},
				path = {
					name = "path",
					module = "blink.cmp.sources.path",
					enabled = true,
					score_offset = 3,
					opts = {
						trailing_slash = false,
						label_trailing_slash = true,
						get_cwd = function(ctx)
							return vim.fn.expand(("#%d:p:h").format(ctx.bufnr))
						end,
						show_show_hidden_files_by_default = true,
					},
					should_show_items = true,
                    fallbacks = { 'lazydev' }
				},
				snippets = {
					name = "Snip",
					module = "blink.cmp.sources.snippets",
					enabled = true,
					score_offset = -3,
					opts = {
						friendly_snippets = true,
						search_paths = { vim.fn.stdpath("config") .. "/snippets" },
					},
				},
				buffer = {
					name = "buffer",
					module = "blink.cmp.sources.buffer",
					score_offset = -5,
				},
				lazydev = {
					name = "lazydev",
					module = "lazydev.integrations.blink",
					fallbacks = { "lsp" },
				},
				luasnip = {
					name = "luasnip",
					module = "blink.cmp.sources.luasnip",
					opts = {
						show_autosnipppets = true,
						use_show_condition = true,
					},
				},
			},
		},
		appearance = {
			highlight_ns = vim.api.nvim_create_namespace("blink_cmp"),
			use_nvim_cmp_as_default = false,
			nerd_font_variant = "mono",
			kind_icons = {
				Array = "󰅪",
				Boolean = "",
				Class = "",
				Color = "",
				Constant = "",
				Constructor = "",
				Enum = "",
				EnumMember = "",
				Event = "",
				Field = "",
				File = "",
				Folder = "",
				Function = "󰡱",
				Interface = "",
				Key = "",
				Keyword = "",
				Method = "",
				Module = "",
				Namespace = "",
				Null = "󰟢",
				Number = "",
				Object = "",
				Operator = "",
				Package = "",
				Property = "󰯠",
				Reference = "",
				Snippet = "󰩫",
				String = "",
				Struct = "",
				Text = "󰦪",
				TypeParameter = "",
				Unit = "",
				Value = "",
				Variable = "󰫧",
			},
		},
	})
end

return Plugin
```

### neovim version

latest git 

### `blink.cmp` version: branch, tag, or commit

latest git

**Comment by Saghen** [comment] 2024-12-24 20:40
Duplicate of #657

**Comment by the-fuckin-nobody** [comment] 2024-12-25 05:26
Are both the issues that I addressed, related to #657 ? And if you don't mind, may I know how(just curious)?

Thank You.

**Comment by Saghen** [comment] 2024-12-25 16:50
Ah you're right, the menu should still appear on `./foo.|`

**Closed** 2024-12-31 16:58 UTC
Labels: bug, sources

**Comment by the-fuckin-nobody** [comment] 2025-01-01 04:55
Thanks, works fine now!

Happy New Year ;-)
