### ISSUE TITLE
Scroll bar for documentation window not scroll

### ISSUE THREAD

**Issue by Kaiser-Yang** [Saghen/blink.cmp#709] opened 2024-12-22 04:55 UTC
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

When I scroll down, the scroll bar is not updated:

![image](https://github.com/user-attachments/assets/0ed4741f-661c-456c-ac41-ea804267af11)

### Relevant configuration

```lua
completion = {
                menu = {
                    border = 'rounded',
                    max_height = 15,
                    scrolloff = 0,
                },
                documentation = {
                    auto_show = true,
                    auto_show_delay_ms = 0,
                    window = {
                        border = 'rounded'
                    }
                },
            },
            keymap = {
                ['<c-u>'] = { 'scroll_documentation_up', 'fallback' },
                ['<c-d>'] = { 'scroll_documentation_down', 'fallback' },
            },
```

### neovim version

NVIM v0.10.1

### `blink.cmp` version: branch, tag, or commit

v0.8.1

**Comment by Saghen** [comment] 2024-12-22 05:17
Duplicate of #684

**Closed by Saghen** 2024-12-22 05:17 UTC
Labels: bug
