### ISSUE TITLE
Autocompletion suggestions that should not show at the top is at the top instead of the convenient one. + a new Error.

### ISSUE THREAD

**Issue by leet0rz** [Saghen/blink.cmp#391] opened 2024-11-27 12:37 UTC
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

![643kO0N](https://github.com/user-attachments/assets/85094fde-c0ae-4b74-af03-4c815a548407)

As you can see from the picture printf is all the way at the bottom when it should be at the top as it is by far the most commonly used out of the ones we can see, I See this in other suggestions too where a lot of stuff with underscores will show up at the top meanwhile the stuff you are looking for are all at the bottom. Any quick fixes to this?

Edit: Also after updating to 0.6.1 I started getting this error:

```lua
Error executing vim.schedule lua callback: ...al/nvim-data/lazy/blink.cmp/lua/blink/cmp/fuzzy/init.lua:24: attempt to call field 'fuzzy_matched_indices' (a nil value)
stack traceback:
        ...al/nvim-data/lazy/blink.cmp/lua/blink/cmp/fuzzy/init.lua:24: in function 'fuzzy_matched_indices'
        .../lazy/blink.cmp/lua/blink/cmp/windows/render/context.lua:21: in function 'get_from_items'
        ...ata/lazy/blink.cmp/lua/blink/cmp/windows/render/init.lua:54: in function 'draw'
        ...ta/lazy/blink.cmp/lua/blink/cmp/windows/autocomplete.lua:111: in function 'open_with_items'
        ...ta/Local/nvim-data/lazy/blink.cmp/lua/blink/cmp/init.lua:57: in function <...ta/Local/nvim-data/lazy/blink.cmp/lua/blink/cmp/init.lua:51>
```

Same config.

### Relevant configuration

```lua
"saghen/blink.cmp",
			lazy = false, -- lazy loading handled internally
			version = "v0.*",
			opts = {
				},
				highlight = {
					use_nvim_cmp_as_default = true,
				},
				nerd_font_variant = "mono",
				sources = {
					completion = {
						enabled_providers = {
							"lsp",
							"snippets",
							"path",
							-- 'buffer'
						},
					},
				},
				windows = {
					autocomplete = {
						min_width = 40,
						max_height = 20,
						border = "rounded",
					},
					documentation = {
						border = "rounded",
						auto_show = true,
					},
					signature_help = {
						border = "rounded",
					},
				},
 			},
		},
```

### neovim version

NVIM v0.11.0-dev-1090+g99acc9de55 Build type: RelWithDebInfo LuaJIT 2.1.1727870382 Run "nvim -V1 -v" for more info

### `blink.cmp` version: branch, tag, or commit

0.6.0

**Comment by Saghen** [comment] 2024-11-27 20:55
Duplicate of #365 and #68

**Closed by Saghen** 2024-11-27 20:55 UTC
Labels: bug
