### ISSUE TITLE
Support for LuaSnip as snippets engine

### ISSUE THREAD

**Issue by alienman5k** [Saghen/blink.cmp#62] opened 2024-10-09 16:24 UTC
The request is to add support for LuaSnip engine to provide snippets. It seems to me that only friendly-snippets is supported but I don't see how to integrate with LuaSnip.

**Comment by Saghen** [comment] 2024-10-09 16:35
LuaSnip seems out of scope for the built-in snippets provider, which supports `vim.snippet` and vscode-style snippet definitions. I'll leave this to the community to implement as an external provider

**Comment by alienman5k** [comment] 2024-10-09 20:21
Any documentation on how to build different providers available? Or is that a future feature?

**Comment by Saghen** [comment] 2024-10-09 20:42
Not yet but it'll be done before 1.0

**Comment by leiserfg** [comment] 2024-10-13 20:01
The problem is that having only a provider will make it so lsp snippets will use the internal engine, therefore mappings won't work the same.

**Comment by Saghen** [comment] 2024-10-21 00:16
Using this issue to track support for an `accept.expand_snippet` function

**Comment by Saghen** [comment] 2024-11-08 14:39
Closed by #286

**Closed by Saghen** 2024-11-08 14:39 UTC
Labels: feature
