### ISSUE TITLE
Repeat last action doesn't work properly with auto_insert

### ISSUE THREAD

**Issue by RishabhRD** [Saghen/blink.cmp#775] opened 2024-12-25 16:44 UTC
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

First of all thanks for the great plugin.
I have auto_insert enabled on selection.

Steps to reproduce:
1. Type `ret` and let's say we got `return` as completion in completion menu.
2. So I used <C-n> to go to reach that completion.
3. However, I don't press <C-y> to confirm that selection, as I have auto_insert enabled, I would get `return` in buffer.
4. Now, Press <Esc> and press `.`. You would see only ret has been added to buffer as part of last action. However, I expected it to be return.

### Relevant configuration

```lua
return {
  {
    "saghen/blink.cmp",
    dependencies = {
      "L3MON4D3/LuaSnip",
      version = "v2.*",
      --"giuxtaposition/blink-cmp-copilot",
    },
    version = "*",
    opts = {
      enabled = function()
        return vim.tbl_contains({}, vim.bo.filetype)
          and vim.bo.buftype ~= "prompt"
          and vim.bo.buftype ~= "cmdline"
          and vim.b.completion ~= false
      end,
      completion = {
        list = {
          selection = function(_)
            return "auto_insert"
          end,
        },
        trigger = {
          show_on_insert_on_trigger_character = true,
          show_on_keyword = true,
          show_on_trigger_character = true,
          show_on_accept_on_trigger_character = true,
        },
        menu = {
          auto_show = function(_)
            return true
          end,
        },
        ghost_text = {
          enabled = false, -- Shows current selection as virtual text
        },
        documentation = {
          auto_show = true,
          auto_show_delay_ms = 300,
        },
      },
      keymap = { preset = "default" },

      appearance = {
        -- use_nvim_cmp_as_default = true,
        nerd_font_variant = "normal",
      },
      sources = {
        cmdline = {},
        default = {
          "lsp",
          "path",
          "luasnip",
          "buffer",
          -- "copilot",
        },
        providers = {
          lsp = {
            name = "LSP",
            score_offset = 1000,
            module = "blink.cmp.sources.lsp",
          },
          -- copilot = {
          --   name = "copilot",
          --   module = "blink-cmp-copilot",
          --   score_offset = 2000,
          --   async = true,
          --   enabled = false,
          -- },
        },
      },
      signature = { enabled = true },
      snippets = {
        expand = function(snippet)
          require("luasnip").lsp_expand(snippet)
        end,
        active = function(filter)
          if filter and filter.direction then
            return require("luasnip").jumpable(filter.direction)
          end
          return require("luasnip").in_snippet()
        end,
        jump = function(direction)
          require("luasnip").jump(direction)
        end,
      },
    },
    opts_extend = { "sources.default" },
  },
}
```

### neovim version

NVIM v0.11.0-dev-1249+g146b8300a1 Build type: RelWithDebInfo LuaJIT 2.1.1731601260 Run "nvim -V1 -v" for more info

### `blink.cmp` version: branch, tag, or commit

v0.8.2

**Comment by Saghen** [comment] 2024-12-25 16:47
Duplicate of #182

**Closed by Saghen** 2024-12-25 16:47 UTC
Labels: bug
