### ISSUE TITLE
Keymap: Accept on <CR> not working

### ISSUE THREAD

**Issue by zivkovicn** [Saghen/blink.cmp#35] opened 2024-10-08 15:02 UTC
Hello!

Was testing out the plugin, with next config: 

```
return {
  "saghen/blink.cmp",
  lazy = false, -- lazy loading handled internally
  -- optional: provides snippets for the snippet source
  dependencies = "rafamadriz/friendly-snippets",

  -- use a release tag to download pre-built binaries
  version = "v0.*",
  -- OR build from source, requires nightly: https://rust-lang.github.io/rustup/concepts/channels.html#working-with-nightly-rust
  -- build = 'cargo build --release',

  opts = {
    highlight = {
      -- sets the fallback highlight groups to nvim-cmp's highlight groups
      -- useful for when your theme doesn't support blink.cmp
      -- will be removed in a future release, assuming themes add support
      use_nvim_cmp_as_default = true,
    },
    -- set to 'mono' for 'Nerd Font Mono' or 'normal' for 'Nerd Font'
    -- adjusts spacing to ensure icons are aligned
    nerd_font_variant = "normal",
    keymap = {
      accept = "<cr>",
    },

    -- experimental auto-brackets support
    -- accept = { auto_brackets = { enabled = true } }

    -- experimental signature help support
    -- trigger = { signature_help = { enabled = true } }
  },
}
```

the accept for completion is not triggered on <CR>.

When I update `accept = <c-y>`, then it is working, but still on enter is not.

Thanks!

**Comment by Saghen** [comment] 2024-10-08 15:05
Duplicate of #20

**Closed by Saghen** 2024-10-08 15:05 UTC
