### ISSUE TITLE
bug: autocompletion menu overlapping documentation after selecting from list

### ISSUE THREAD

**Issue by idelice** [Saghen/blink.cmp#212] opened 2024-10-29 22:04 UTC
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

As the title says, the autocompletion menu is overlapping the documentation menu after selecting an item and are in insert mode.

<img width="1140" alt="Screenshot 2024-10-29 at 22 58 58" src="https://github.com/user-attachments/assets/8f10765a-4018-4c21-975e-23ea609edcc4">

### Steps-to-achieve
1. open tsx file
2. type `React` and select `useEffect`
3. You are now in insert mode inside the parentheses 

### Expectation
1. The autocompletion menu shouldn't overlap the documentation
2. The autocompletion shouldn't appear as there are nothing to autocomplete besides free text?

### Relevant configuration

```lua
4 client(s) attached to this buffer

- Client: `vtsls` (id: 1, bufnr: [1])
- Client: `emmet_language_server` (id: 2, bufnr: [1])
- Client: `tailwindcss` (id: 3, bufnr: [1])
- Client: `eslint` (id: 4, bufnr: [1])
```

### neovim version

0.10.1

### `blink.cmp` version: branch, tag, or commit

f0f26728c3e5

**Comment by Saghen** [comment] 2024-10-30 16:00
> The autocompletion menu shouldn't overlap the documentation
Duplicate of #45 

> The autocompletion shouldn't appear as there are nothing to autocomplete besides free text?
Resolved in the above commit

**Closed by Saghen** 2024-10-30 16:00 UTC
Labels: bug
