### ISSUE TITLE
Pressing any key in insert mode quits neovim

### ISSUE THREAD

**Issue by kryptamine** [Saghen/blink.cmp#218] opened 2024-10-30 17:48 UTC
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

I've just updated to the new version, set keymap to default.
Pressing any key in insert mode quits neovim

### Relevant configuration

```lua
return {
  {
    'saghen/blink.cmp',
    lazy = false,
    version = 'v0.*',
    opts = {
      keymap = 'default',
      sources = {
        providers = {
          buffer = {
            fallback_for = {},
            max_items = 4,
            min_keyword_length = 1,
            score_offset = -3,
          },
        },
      },
      highlight = {
        -- sets the fallback highlight groups to nvim-cmp's highlight groups
        -- useful for when your theme doesn't support blink.cmp
        -- will be removed in a future release, assuming themes add support
        use_nvim_cmp_as_default = false,
      },
      -- set to 'mono' for 'Nerd Font Mono' or 'normal' for 'Nerd Font'
      -- adjusts spacing to ensure icons are aligned
      nerd_font_variant = 'mono',
    },
  },
}
```

### neovim version

v0.10.2

### `blink.cmp` version: branch, tag, or commit

5.0.0

**Comment by Saghen** [comment] 2024-10-30 17:53
What's your OS?

**Comment by kryptamine** [comment] 2024-10-30 17:54
mac os

**Comment by Saghen** [comment] 2024-10-30 17:57
Does re-installing the plugin solve the issue for you? And if not, does adding `build = "cargo build --release"` fix the issue?

**Comment by kryptamine** [comment] 2024-10-30 18:01
I dont know what exactly did fix the issue, but adding build = "cargo build --release" and re-installing the plugin has helped

**Comment by Saghen** [comment] 2024-10-30 18:03
Seems like a duplicate of #68

**Closed by Saghen** 2024-10-30 18:03 UTC
Labels: bug
