### ISSUE TITLE
Doc window pops up below the completion menu instead of being on the right

### ISSUE THREAD

**Issue by arztareef** [Saghen/blink.cmp#285] opened 2024-11-07 13:24 UTC
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

![image](https://github.com/user-attachments/assets/fe600605-c20a-4d81-b1df-7252ef56326e)

### Relevant configuration

```lua
window = {
        documentation = {
          scrollbar = false,
          auto_show = true,
        },
}
```

### neovim version

NVIM v0.11.0-dev-1106+gf7e32fb6e6

### `blink.cmp` version: branch, tag, or commit

v0.*

**Comment by Saghen** [comment] 2024-11-07 21:02
This might be fixed in https://github.com/Saghen/blink.cmp/commit/683c47ac8c6e538122dc0fe50187b78f8995a549 since much of the window placement logic was reworked

**Comment by Saghen** [comment] 2024-11-09 01:42
Was able to reproduce it and confirmed that it was fixed on my system. Lmk if you're still having trouble on main!

**Closed** 2024-11-09 01:41 UTC
Labels: bug, windows

**Comment by arztareef** [comment] 2024-11-09 05:03
still happening

**Comment by wilsonchen719** [comment] 2024-12-15 18:52
Happens to me too
