### ISSUE TITLE
fallback of blink <cr> keymap would run <c-m> keymap

### ISSUE THREAD

**Issue by s1n7ax** [Saghen/blink.cmp#766] opened 2024-12-25 05:18 UTC
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

First of all, I had `<cr>` and `<c-m>` mapped to nvim-cmp accept and luasnip previous jump previously before Lazyvim migrated to blink.

From what I can see, those two are distinguishable from each other on kitty and on alacritty with extra keycode fix.

```
nmap <c-m> :echo 'cm'<cr>
nmap <cr> :echo 'cr'<cr>
```

However, I'm not sure if it's distinguishable programmatically in blink's fallback function. Either way, when I have `<c-m>` is mapped while `['<cr>'] = { 'select_and_accept', 'fallback' }`, fallback supposed to add a new line but seem to run `<c-m>` function.

### Relevant configuration

```lua
{
	'saghen/blink.cmp',
	opts = {
		signature = { enabled = true },
		sources = {
			compat = {},
			default = { 'lsp', 'path', 'snippets', 'buffer' },
			cmdline = {},
		},
		keymap = {
			preset = 'enter',
			['<c-n>'] = { 'select_next', 'fallback' },
			['<c-e>'] = { 'select_prev', 'fallback' },
			['<cr>'] = { 'select_and_accept', 'fallback' },
		},
	},
}
```

### neovim version

v0.11.0-dev

### `blink.cmp` version: branch, tag, or commit

0.8.2

**Comment by Saghen** [comment] 2024-12-25 05:24
Can you send a minimal repro: https://lazy.folke.io/developers#reprolua

**Comment by Saghen** [comment] 2024-12-29 01:35
Closing because it seems to be an issue with your configuration. If you're able to create a minimal reproduction for this, I can take another look

**Closed by Saghen** 2024-12-29 01:35 UTC
Labels: bug
