### ISSUE TITLE
Bug Report: Error When Loading float32 Documentation (attempt to index local 'line' (a nil value))

### ISSUE THREAD

**Issue by dme86** [Saghen/blink.cmp#363] opened 2024-11-23 09:18 UTC
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

When using the blink.cmp plugin in a Go project, an error occurs while loading the documentation for float32. 
```go
Error executing vim.schedule lua callback: ...e/nvim/lazy/blink.cmp/lua/blink/cmp/windows/lib/docs.lua:161: attempt to index local 'line' (a nil value)
stack traceback:
	...e/nvim/lazy/blink.cmp/lua/blink/cmp/windows/lib/docs.lua:161: in function 'get_code_block_range'
	...e/nvim/lazy/blink.cmp/lua/blink/cmp/windows/lib/docs.lua:217: in function 'extract_detail_from_doc'
	...e/nvim/lazy/blink.cmp/lua/blink/cmp/windows/lib/docs.lua:20: in function 'render_detail_and_documentation'
	...m/lazy/blink.cmp/lua/blink/cmp/windows/documentation.lua:61: in function 'fn'
	.../nvim/lazy/blink.cmp/lua/blink/cmp/sources/lib/async.lua:86: in function 'cb'
	.../nvim/lazy/blink.cmp/lua/blink/cmp/sources/lib/async.lua:44: in function 'cb'
	.../nvim/lazy/blink.cmp/lua/blink/cmp/sources/lib/async.lua:44: in function 'resolve'
	...zy/blink.cmp/lua/blink/cmp/sources/lib/provider/init.lua:130: in function <...zy/blink.cmp/lua/blink/cmp/sources/lib/provider/init.lua:130>
```

### Relevant configuration

```lua
documentation = {
        min_width = 15,
        max_width = 50,
        max_height = 20,
	auto_show = true,
        border = 'rounded',
        direction_priority = {
          autocomplete_north = { 'e', 'w', 'n', 's' },
          autocomplete_south = { 'e', 'w', 's', 'n' },
        },
      },
```

### neovim version

v0.10.2

### `blink.cmp` version: branch, tag, or commit

v0.5.1

**Comment by Saghen** [comment] 2024-11-24 19:04
Duplicate of #270, resolved in the latest release (`v0.6.0`)

**Closed by Saghen** 2024-11-24 19:04 UTC
Labels: bug
