### ISSUE TITLE
completion menu

### ISSUE THREAD

**Issue by nsxz1234** [Saghen/blink.cmp#554] opened 2024-12-14 03:50 UTC
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

completion menu did not auto disappear
blink

https://github.com/user-attachments/assets/bbdb131a-e8e2-45b6-8e36-034a12f83559

cmp

https://github.com/user-attachments/assets/2eb3f3f4-ceb2-48ef-8b23-8e1d3ee4d339

### neovim version

NVIM v0.11.0-dev-1276+gae93c7f369

### `blink.cmp` version: branch, tag, or commit

main

**Comment by Saghen** [comment] 2024-12-14 03:54
Duplicate of #545

**Closed by Saghen** 2024-12-14 03:54 UTC
Labels: bug
