### ISSUE TITLE
error: list.lua:81: loop or previous error loading module 'blink.cmp.fuzzy'

### ISSUE THREAD

**Issue by lost22git** [Saghen/blink.cmp#623] opened 2024-12-17 18:36 UTC
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

```
   Error  02:21:15 msg_show.lua_error Error executing vim.schedule lua callback: ...re/nvim/lazy/blink.cmp/lua/blink/cmp/completion/list.lua:81: loop or previous error loading module 'blink.cmp.fuzzy'
stack traceback:
	[C]: in function 'require'
	...re/nvim/lazy/blink.cmp/lua/blink/cmp/completion/list.lua:81: in function 'fuzzy'
	...re/nvim/lazy/blink.cmp/lua/blink/cmp/completion/list.lua:68: in function 'show'
	...re/nvim/lazy/blink.cmp/lua/blink/cmp/completion/init.lua:32: in function <...re/nvim/lazy/blink.cmp/lua/blink/cmp/completion/init.lua:29>
```

### Relevant configuration

```lua
return {
  "saghen/blink.cmp",
  lazy = false,
  dependencies = "rafamadriz/friendly-snippets",
  version = "v0.*",

  opts = {
    keymap = "default"
    appearance = {
      use_nvim_cmp_as_default = true,
      nerd_font_variant = "mono",
    },
    sources = {
      default = { "lsp", "path", "snippets", "buffer" },
    },
    signature = { enabled = true },
  },
  opts_extend = { "sources.default" },
}
```

### neovim version

NVIM v0.10.2 Build type: Release LuaJIT 2.1.1727870382 

### `blink.cmp` version: branch, tag, or commit

version: 0.7.6 , tag: v0.7.6, branch: main, commit: ae5a4ce

**Comment by Saghen** [comment] 2024-12-17 18:40
Likely a duplicate of #68

**Closed by Saghen** 2024-12-17 18:40 UTC
Labels: bug
