### ISSUE TITLE
Support for Snippet Choices and Custom Keymap in Blink.cmp

### ISSUE THREAD

**Issue by krovuxdev** [Saghen/blink.cmp#785] opened 2024-12-26 04:03 UTC
### Feature Description

**Merry Christmas, Saghen :)**

I think the `completion/completeopt` settings should be modified to support `blink.cmp` as a completion source, because Blink does not currently provide autocompletion for snippet choices.

It would be a good idea to add a custom keymap for snippet choices, something like `["<C-E>"] = { "expandchoice" }`.

I understand that someone might suggest using `luasnip` or `mini.snippet`, but this doesn't mean it should depend on those. Instead, a new keymap, such as `expandchoice`, specific for Blink, along with customizable `completeopt` options, would be a great idea for the future.

It would be really interesting to see this feature added!

https://github.com/user-attachments/assets/a3f5992a-7c7d-4702-b73b-9316a2aa4db7

**Comment by Saghen** [comment] 2024-12-29 19:44
Merry christmas to you too :)

Duplicate of #743

**Closed by Saghen** 2024-12-29 19:43 UTC
Labels: feature
