### ISSUE TITLE
Have the completion list in reverse order.

### ISSUE THREAD

**Issue by arnevm123** [Saghen/blink.cmp#720] opened 2024-12-22 10:18 UTC
### Feature Description

Hi, 
Is there a possibility to have the selected completion item to always be the closest to the cursor?
So when using the  `direction_priority = { "n", "s" }`  `true` would be at the bottom of the list and selected in the attached picture?

I have checked the configuration and did not find an option for this.
Or is this something that is not possible at the moment?

![image](https://github.com/user-attachments/assets/af715caf-9bec-4f65-854b-9c421a5a420f)

**Comment by Saghen** [comment] 2024-12-23 05:52
Duplicate of #206

**Closed by Saghen** 2024-12-23 05:52 UTC
Labels: feature
