### ISSUE TITLE
Simultaneous triggering when I set <cr> accpet

### ISSUE THREAD

**Issue by Kicamon** [Saghen/blink.cmp#788] opened 2024-12-26 11:49 UTC
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

I set <cr> accpet, when I type <cr> in command mode, is simultanous triggering completion accpet and execute command

### Relevant configuration

```lua
keymap = {
      ['<Tab>'] = {
        'select_next',
        'snippet_forward',
        function(cmp)
          if has_words_before() then
            return cmp.show()
          end
        end,
        'fallback',
      },
      ['<S-Tab>'] = { 'select_prev', 'snippet_backward', 'fallback' },
      ['<CR>'] = { 'accept', 'fallback' },
    },
```

### neovim version

0.10.3

### `blink.cmp` version: branch, tag, or commit

v0.*

**Comment by Saghen** [comment] 2024-12-29 00:34
A lot of people had to create workarounds to get that behavior :smile: This seems to be an issue with your config, are you able to reproduce it in a minimal reproduction? https://lazy.folke.io/developers#reprolua

**Comment by Saghen** [comment] 2024-12-31 18:12
Closing for now but I'll take another look if you provide that minimal repro

**Closed by Saghen** 2024-12-31 18:12 UTC
Labels: bug, keymap
