### ISSUE TITLE
Error with `set_provider_items`

### ISSUE THREAD

**Issue by somokill** [Saghen/blink.cmp#701] opened 2024-12-21 16:39 UTC
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

![image](https://github.com/user-attachments/assets/3c34dfed-9782-4d32-82e2-956569e0b036)
**after update** i get following error related to `fuzzy`

### Relevant configuration

```lua
sources = {
  default = { "lsp", "path", "luasnip", "buffer" }
},
```

### neovim version

NVIM v0.10.2 Build type: Release LuaJIT 2.1.1713773202

### `blink.cmp` version: branch, tag, or commit

v0.8.0

**Comment by Saghen** [comment] 2024-12-21 18:35
A re-install should fix the issue. I'm hopeful that the downloader won't break between versions in the future

Duplicate of #68

**Closed by Saghen** 2024-12-21 18:35 UTC
Labels: bug

**Comment by olimorris** [comment] 2024-12-22 21:51
Can confirm a reinstall worked for me.

**Comment by Saghen** [comment] 2024-12-22 21:57
Did you happen to build locally with `cargo build --release`? @olimorris

**Comment by olimorris** [comment] 2024-12-22 22:05
Sorry should have been specific. That's exactly what I did.
