### ISSUE TITLE
`vim.snippets.expand` overrides blink.cmp's `<Tab>` mapping in nightly Neovim

### ISSUE THREAD

**Issue by metiulekm** [Saghen/blink.cmp#804] opened 2024-12-27 19:23 UTC
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

That function creates `<Tab>` and `<S-Tab>` mappings unconditionally, it's as simple as that :) This has been reported to Neovim in https://github.com/neovim/neovim/issues/30198. This is new in nightly, this does not happen in NVIM v0.10.3.

In case of blink.cmp, this means that for example, when using the `"super-tab"` preset, we expand a snippet, and then try to complete via Tab still inside the snippet, we jump to the next placeholder. See for instance this recording, where I pressed Tab twice to accept both `fprintf` and then `stderr`: 

https://github.com/user-attachments/assets/7c1a0a17-e3b8-49c5-9e5f-858207bca642

There is a hacky fix in https://github.com/neovim/neovim/issues/30198#issuecomment-2326075321, copying it fixes the issue. Considering that the https://github.com/neovim/neovim/issues/30198 issue is probably not going to be fixed anytime soon, maybe copying this fix to blink.cmp or adding a note to https://cmp.saghen.dev/configuration/keymap.html might be worthwhile?

### Relevant configuration

```lua
-- Full blink.cmp configuration in the recording above
keymap = {
    preset = "super-tab",
},
sources = {
    default = { "lsp" },
},
```

### neovim version

NVIM v0.11.0-nightly+487c48e

### `blink.cmp` version: branch, tag, or commit

Happens both on v0.8.2 and 434ea2b05c2bae0cff6249893c8324fa3a56d865

**Comment by Saghen** [comment] 2024-12-27 19:27
Duplicate of #289

**Closed by Saghen** 2024-12-27 19:27 UTC
Labels: bug

**Comment by metiulekm** [comment] 2024-12-27 19:36
Oh, so sorry about that :( Admittedly I only really searched for `vim.snippet`…
