### ISSUE TITLE
Error: attempt to call field 'fuzzy_matched_indices' (a nil value) 

### ISSUE THREAD

**Issue by jasmine-nguyen** [Saghen/blink.cmp#376] opened 2024-11-25 00:47 UTC
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

<img width="1510" alt="Screenshot 2024-11-25 at 11 27 22 AM" src="https://github.com/user-attachments/assets/b7e87de5-d8f3-4dd7-a1a4-a297b4031fb0">

After upgrading to v.0.6.1, I started to encounter this error. 

### Relevant configuration

```lua
I don't set any custom setting for fuzzy matching. Only use the default setting
```

### neovim version

v.0.10.2

### `blink.cmp` version: branch, tag, or commit

v.0.6.1

**Comment by Saghen** [comment] 2024-11-25 00:51
Duplicate of #375 which was a duplicate of #68

**Closed by Saghen** 2024-11-25 00:51 UTC
Labels: bug
