### ISSUE TITLE
Cmdline completion

### ISSUE THREAD

**Issue by fredrikaverpil** [Saghen/blink.cmp#340] opened 2024-11-16 20:24 UTC
### Feature Description

It would be awesome to enable something like [cmp-cmdline](https://github.com/hrsh7th/cmp-cmdline) but for blink. This is the `#1` thing I miss from nvim-cmp.

https://github.com/user-attachments/assets/5ba0daea-294f-4695-91f2-ad90c55c47c1

I saw in the README you mentioned you wanted to implement this 🎉 but I figured we could track progress of it here. 😄 

### Workaround

As a workaround, I'm using cmp-cmdline in tandem with blink now. Source:
* [cmp.lua](https://github.com/fredrikaverpil/dotfiles/blob/2a7a076040f339840e02a2f20b5d8c9c1b0bc3cc/nvim-fredrik/lua/plugins/cmp.lua)
* [blink.lua](https://github.com/fredrikaverpil/dotfiles/blob/2a7a076040f339840e02a2f20b5d8c9c1b0bc3cc/nvim-fredrik/lua/plugins/blink.lua)

<img width="1254" alt="image" src="https://github.com/user-attachments/assets/75935acd-be8a-40de-9c3a-c05569e094b6">

**Comment by Saghen** [comment] 2024-11-16 21:07
Duplicate of #138

**Closed by Saghen** 2024-11-16 21:07 UTC
Labels: feature
