### ISSUE TITLE
cmdline: Multi-argument completions include duplicate prefix

### ISSUE THREAD

**Issue by b0o** [Saghen/blink.cmp#555] opened 2024-12-14 06:32 UTC
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

Accepting a completion for certain command arguments results in the prefix being prepended to the completion text. For example:

With `:lua`:

1. initial: `:lua vim.no`
2. accept completion for vim.notify
3. actual: `:lua vim.vim.notify`
4. expected: `:lua vim.notify`

With `:set`:

1. initial: `:set ft=lu`
2. accept completion for lua
3. actual: `:set ft=ft=lua`
4. expected: `:set ft=lua`

Similar behavior when completing filepaths e.g. `:e /etc`, lua expression inspecting e.g. `:=vim.notify`, and probably others.

### Relevant configuration

Default settings. Tested with `default`, `super-tab`, and `enter` cmdline mappings presets.

### neovim version

`NVIM v0.11.0-dev-1273+g7a367c6967`

### `blink.cmp` version: branch, tag, or commit

`217f670`

**Comment by the-fuckin-nobody** [comment] 2024-12-14 10:12
This is a duplicate of #46 and #541, I guess.

**Comment by b0o** [comment] 2024-12-14 10:22
Ah, thanks, I should have checked more closely.

**Closed** 2024-12-14 11:21 UTC
Labels: bug
