### ISSUE TITLE
Blink enabled in telescope when opening from alpha-nvim

### ISSUE THREAD

**Issue by matteobongio** [Saghen/blink.cmp#731] opened 2024-12-23 13:04 UTC
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

When I open telescope from alpha nvim, blink is enabled, but when I launch telescope from a normal buffer, blink is not (which is the desired behavior)

### Relevant configuration

```lua
-- from blink
    enabled = function()
      return not vim.tbl_contains({ "markdown" }, vim.bo.filetype)
          and vim.bo.buftype ~= "prompt"
          and vim.b.completion ~= false
    end,

-- from alpha 
    dashboard.section.buttons.val = {
      dashboard.button("f", " " .. " Find file", ":Telescope find_files <CR>"),
      dashboard.button("r", "󰄉 " .. " Recent files", ":Telescope oldfiles <CR>"),
      dashboard.button("g", " " .. " Find text", ":Telescope live_grep <CR>"),
    }
```

### neovim version

NVIM v0.10.2

### `blink.cmp` version: branch, tag, or commit

v0.8.1

**Comment by Saghen** [comment] 2024-12-23 21:13
Duplicate of #716

**Closed by Saghen** 2024-12-23 21:13 UTC
Labels: bug
