### ISSUE TITLE
v0.7.1 makes neovim quit

### ISSUE THREAD

**Issue by gogamid** [Saghen/blink.cmp#431] opened 2024-12-03 09:26 UTC
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

neovim quits after the new changes in the blink completion. I get first 

```
position_encoding param is required in vim.lsp.util.make_range_params. Defaulting to position encoding of the first client.
```
then whenever i type something, neovim quits.

Has anyone experienced this?

### Relevant configuration

```lua
return {
  {
    "hrsh7th/nvim-cmp",
    enabled = false,
  },
  {
    "saghen/blink.cmp",
    version = not vim.g.lazyvim_blink_main and "*",
    build = vim.g.lazyvim_blink_main and "cargo build --release",
    opts_extend = {
      "sources.completion.enabled_providers",
      "sources.compat",
    },
    dependencies = {
      "rafamadriz/friendly-snippets",
      -- add blink.compat to dependencies
      {
        "saghen/blink.compat",
        optional = true, -- make optional so it's only enabled if any extras need it
        opts = {},
        version = not vim.g.lazyvim_blink_main and "*",
      },
    },
    event = "InsertEnter",

    ---@module 'blink.cmp'
    ---@type blink.cmp.Config
    opts = {
      highlight = {
        -- sets the fallback highlight groups to nvim-cmp's highlight groups
        -- useful for when your theme doesn't support blink.cmp
        -- will be removed in a future release, assuming themes add support
        use_nvim_cmp_as_default = false,
      },
      -- set to 'mono' for 'Nerd Font Mono' or 'normal' for 'Nerd Font'
      -- adjusts spacing to ensure icons are aligned
      nerd_font_variant = "mono",
      completion = {
        menu = {
          winblend = vim.o.pumblend,
          draw = { treesitter = true },
        },
        documentation = {
          auto_show = true,
          auto_show_delay_ms = 200,
        },
        ghost_text = {
          enabled = vim.g.ai_cmp,
        },
      },

      -- experimental auto-brackets support
      accept = { auto_brackets = { enabled = true } },

      -- experimental signature help support
      -- trigger = { signature_help = { enabled = true } }
      sources = {
        -- adding any nvim-cmp sources here will enable them
        -- with blink.compat
        compat = {},
        completion = {
          -- remember to enable your providers here
          enabled_providers = { "lsp", "path", "snippets", "buffer" },
        },
      },

      keymap = {
        preset = "enter",
        ["<Tab>"] = {
          LazyVim.cmp.map({ "snippet_forward", "ai_accept" }),
          "fallback",
        },
      },
    },
    ---@param opts blink.cmp.Config | { sources: { compat: string[] } }
    config = function(_, opts)
      -- setup compat sources
      local enabled = opts.sources.completion.enabled_providers
      for _, source in ipairs(opts.sources.compat or {}) do
        opts.sources.providers[source] = vim.tbl_deep_extend(
          "force",
          { name = source, module = "blink.compat.source" },
          opts.sources.providers[source] or {}
        )
        if type(enabled) == "table" and not vim.tbl_contains(enabled, source) then
          table.insert(enabled, source)
        end
      end
      require("blink.cmp").setup(opts)
    end,
  },

  -- add icons
  {
    "saghen/blink.cmp",
    opts = function(_, opts)
      opts.appearance = opts.appearance or {}
      opts.appearance.kind_icons = LazyVim.config.icons.kinds
    end,
  },

  -- lazydev
  {
    "saghen/blink.cmp",
    opts = {
      sources = {
        completion = {
          -- add lazydev to your completion providers
          enabled_providers = { "lazydev" },
        },
        providers = {
          lsp = {
            -- dont show LuaLS require statements when lazydev has items
            fallback_for = { "lazydev" },
          },
          lazydev = {
            name = "LazyDev",
            module = "lazydev.integrations.blink",
          },
        },
      },
    },
  },
  -- catppuccin support
  {
    "catppuccin",
    optional = true,
    opts = {
      integrations = { blink_cmp = true },
    },
  },
}
```

### neovim version

v0.11.0-dev-1272+g3d3a99e69c-Homebrew

### `blink.cmp` version: branch, tag, or commit

v0.7.1

**Comment by benfrain** [comment] 2024-12-03 10:07
Related, also on 0.7.1, when I type <kpd>v</kbd> it quits Neovim and creates a new Terminal window below (using Kitty 0.37, Neovim 10.2, macOS 15.1.1).

**Comment by gogamid** [comment] 2024-12-03 12:49
off topic, love your videos @benfrain  :D

**Comment by benfrain** [comment] 2024-12-03 13:08
> off topic, love your videos @benfrain :D

Oh, thanks so much 🙏 Last one featured blink.cmp so not totally off topic 🤣

**Comment by benfrain** [comment] 2024-12-03 15:55
> Does re-installing fix the issue as per #68? If it does, and you're able to reproduce this issue, please lmk! I've been trying to reproduce this bug for ages

Ha, for me, yes, 'turning it off and back on again' did the trick!

**Comment by Saghen** [comment] 2024-12-03 16:51
Duplicate of #68

**Closed** 2024-12-03 16:50 UTC
Labels: bug
