### ISSUE TITLE
[bug]: Error Fuzzy

### ISSUE THREAD

**Issue by krovuxdev** [Saghen/blink.cmp#711] opened 2024-12-22 05:19 UTC
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

![imagen](https://github.com/user-attachments/assets/c35cb349-3efc-46c1-a59e-48df6162914a)
After updating and changing my configuration, when I press Ctrl + Space or try to enter cmdline, I encounter an error. I'm not sure if it's caused by the new configuration or an issue with the update.

### Relevant configuration

```lua
return {
    "saghen/blink.cmp",
    version = "v0.*",
    opts = {
        keymap = { preset = "default" },
        appearance = {
            use_nvim_cmp_as_default = true,
            nerd_font_variant = "mono",
        },
        sources = {
            default = { "lsp", "path", "snippets", "buffer" },
        },
    },
```

### neovim version

NVIM v0.10.2

### `blink.cmp` version: branch, tag, or commit

v0.8.1

**Comment by Saghen** [comment] 2024-12-22 05:35
Duplicate of #68

**Closed by Saghen** 2024-12-22 05:35 UTC
Labels: bug
