### ISSUE TITLE
[improve] better scoring

### ISSUE THREAD

**Issue by kaiphat** [Saghen/blink.cmp#498] opened 2024-12-11 13:10 UTC
### Feature Description

I prefer to see completions sorted via length. 
Also maybe you could change score calculation such way to improve current case:
I try to find keyword `import` and see a lot of variant.
In my opinion when input is `impor`, then `DynamicsCompressorNode` shouldn't have bigger score than `import`.

https://github.com/user-attachments/assets/71881c9f-d3cc-4c2e-aff9-d3f0ef6273b9

**Comment by kaiphat** [comment] 2024-12-11 13:16
Another example of bad scoring. I try to find `isMapIterator`.

https://github.com/user-attachments/assets/23f06d1f-a000-408a-acac-00af6ec7b505

**Comment by kaiphat** [comment] 2024-12-11 13:26
`v0.7.4` much more better scoring

https://github.com/user-attachments/assets/468b4753-03f0-4fd6-aa5f-6be48a9537a2

**Comment by kaiphat** [comment] 2024-12-11 13:27
![image](https://github.com/user-attachments/assets/8fdf72ca-85f9-49f3-9cd7-69723b246125)

**Comment by kaiphat** [comment] 2024-12-11 13:30
I'm sorry i think it's feature, but it's definitely bug with `0.7.6` version.

**Comment by Saghen** [comment] 2024-12-11 18:13
Duplicate of #497

**Closed by Saghen** 2024-12-11 18:13 UTC
Labels: feature
