### ISSUE TITLE
C# Roslyn lsp error when writing doc string

### ISSUE THREAD

**Issue by quantum-booty** [Saghen/blink.cmp#263] opened 2024-11-04 19:34 UTC
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description
Looks like the lines table can contain nil items.
https://github.com/Saghen/blink.cmp/blob/973f06a164835b74247f46b3c5b2ae895a1acb1b/lua/blink/cmp/windows/lib/docs.lua#L160

Also, I don't think it should be completing keywords inside doc string.

![image](https://github.com/user-attachments/assets/a74c910b-2b7d-4cc0-b45f-b56b0b94ed22)

### Relevant configuration

```lua
{
        'saghen/blink.cmp',
        lazy = false, -- lazy loading handled internally
        version = 'v0.*',
        opts = {
            keymap = {
                ['<CR>'] = { 'accept', 'fallback' },
                ['<S-Tab>'] = { 'select_prev', 'fallback' },
                ['<Tab>'] = { 'select_next', 'fallback' },
                ['<C-b>'] = { 'scroll_documentation_up', 'fallback' },
                ['<C-f>'] = { 'scroll_documentation_down', 'fallback' },
                ['<Up>'] = { 'select_prev', 'fallback' },
                ['<Down>'] = { 'select_next', 'fallback' },
            },

            highlight = {
                -- sets the fallback highlight groups to nvim-cmp's highlight groups
                -- useful for when your theme doesn't support blink.cmp
                -- will be removed in a future release, assuming themes add support
                use_nvim_cmp_as_default = true,
            },
            nerd_font_variant = 'normal',

            accept = { auto_brackets = { enabled = true } },

            windows = {
                autocomplete = {
                    draw = 'reversed',
                },
                documentation = {
                    border = 'single',
                    auto_show = true,
                    auto_show_delay_ms = 50,
                    update_delay_ms = 50,
                },
            },
        },
    },
    {
        "seblj/roslyn.nvim",
        event = { "BufReadPre", "BufNewFile" },
        -- vscode = false,
        ft = "cs",
    },
```

### neovim version

NVIM v0.11.0-dev-1075+gb34e137e43

### `blink.cmp` version: branch, tag, or commit

v0.5.1

**Comment by Saghen** [comment] 2024-11-04 19:42
Duplicate of #247

**Closed by Saghen** 2024-11-04 19:41 UTC
Labels: bug
