### ISSUE TITLE
`cmdline` completion ignores the existing prefix

### ISSUE THREAD

**Issue by kawre** [Saghen/blink.cmp#541] opened 2024-12-13 18:43 UTC
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

https://github.com/user-attachments/assets/37127733-c136-4bf1-96b2-04674e6e2644

### neovim version

NVIM v0.11.0-dev-1287+g8f84167c30

### `blink.cmp` version: branch, tag, or commit

f99b03c

**Comment by kawre** [comment] 2024-12-13 18:53
It would also be great if blink opened the completion window after every space insertion in `cmdline`

**Comment by kawre** [comment] 2024-12-13 19:05
Also, blink doesn't account for live updates to the completion list. Below is an example with `nvim-cmp`: as soon as the `=` character is inserted, the completion list updates. In blink, you have to reopen the menu.

https://github.com/user-attachments/assets/051db0dd-3d77-4ba0-8f8e-c75b9f16e745

**Comment by the-fuckin-nobody** [comment] 2024-12-13 19:07
> It would also be great if blink opened the completion window after every space insertion in cmdline

It does open :
![image](https://github.com/user-attachments/assets/0ce03d7e-ad6b-497a-80d7-50603909c426)

**Comment by the-fuckin-nobody** [comment] 2024-12-13 19:22
> Not in my case then, as shown in the first video provided

Have you blacklisted `whitespace` as triggerchars in the config? Pretty sure  that might be causing it

**Comment by kawre** [comment] 2024-12-13 19:29
> > Not in my case then, as shown in the first video provided
> 
> Have you blacklisted `' '` as triggerchars in the config? Pretty sure that might be causing it

No, same behavior with default configuration

**Comment by Saghen** [comment] 2024-12-13 19:34
I've fixed the issues mentioned in the comments, but the main issue is a duplicate of #46

**Closed by Saghen** 2024-12-13 19:34 UTC
Labels: bug
