### ISSUE TITLE
Trigger JavaDoc snippets

### ISSUE THREAD

**Issue by kevinm6** [Saghen/blink.cmp#823] opened 2024-12-29 22:56 UTC
Hello, I didn't find a similar issue about this.

I can't trigger JavaDoc snippets with prefix '/*' or '/**' using **blink.cmp**, but I was able to do it with **nvim-cmp**.

I'm using a [personal fork](https://github.com/kevinm6/snippets) of friendly-snippets and [these are](https://github.com/kevinm6/snippets/blob/main/snippets/java/javadoc.json#L2-L30) the snippets that I can't trigger with prefix, but I can find and expand them in the completion list.

Is there something that I'm missing? (I've tried, unsuccessfully, to change the regex keyword to match the slash, that it's working fine on _path-completion_)

**Comment by echaya** [comment] 2024-12-30 13:08
I'm facing some prefix issue (but not exact the same) where I have prefix set to `~`, e..g, `~rename`, after triggering the prefix is not removed so it end up with `~.rename({"$1":"$2"})`

The same snippets works with nvim-cmp

**Comment by Saghen** [comment] 2024-12-30 19:25
Duplicate of #46 and #758

**Closed by Saghen** 2024-12-30 19:25 UTC
