### ISSUE TITLE
Tab key mapping lost after snippet expansion due to keymap cache mechanism

### ISSUE THREAD

**Issue by aniaan** [Saghen/blink.cmp#417] opened 2024-12-02 03:30 UTC
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

When using blink.cmp with custom tab key mapping and snippets, the tab key mapping is lost after snippet expansion. This occurs because:

1. Initial setup: Tab key is mapped with custom commands through blink.cmp configuration:
```lua
keymap = {
    preset = "enter",
    ["<Tab>"] = {
        LazyVim.cmp.map({ "snippet_forward", "ai_accept" }),
        "fallback",
    },
}
```

2. When a snippet is expanded, Neovim's native snippet system sets its own mapping for the Tab key
https://github.com/Saghen/blink.cmp/blob/4559ec5cfb91ed8080e2f8df7d4784e12aa27f18/lua/blink/cmp/completion/accept/init.lua#L43-L53

3. After snippet mode ends, the original Tab mapping from blink.cmp is not restored
4. The issue stems from the keymap cache mechanism in `apply.keymap_to_current_buffer`, which skips remapping if any keymap with desc='blink.cmp' exists, even if specific keys (like Tab) have been overwritten
https://github.com/Saghen/blink.cmp/blob/4559ec5cfb91ed8080e2f8df7d4784e12aa27f18/lua/blink/cmp/keymap/apply.lua#L7-L12

## Steps to Reproduce

1. Configure blink.cmp with custom Tab mapping
2. Trigger a completion that expands into a snippet
3. After completing the snippet, try using Tab key
4. The original Tab mapping functionality is lost

## Expected Behavior

After snippet expansion completes, the Tab key should restore its original mapping as configured in blink.cmp.

## Current Behavior

The Tab key mapping remains in its snippet-mode state and doesn't return to the blink.cmp configured behavior.

### Relevant configuration

```lua
keymap = {
    preset = "enter",
    ["<Tab>"] = {
        LazyVim.cmp.map({ "snippet_forward", "ai_accept" }),
        "fallback",
    },
}
```

### neovim version

NVIM v0.11.0-dev-1261+gab9cfc4dc3 
Build type: RelWithDebInfo 
LuaJIT 2.1.1732813678 
Run "nvim -V1 -v" for more info

### `blink.cmp` version: branch, tag, or commit

main

**Comment by Saghen** [comment] 2024-12-02 03:36
Hey there, this sounds like a duplicate of #289

**Closed by Saghen** 2024-12-02 03:36 UTC
Labels: bug
