### ISSUE TITLE
Unable to create new line with enter in Insert-mode in latest version

### ISSUE THREAD

**Issue by arnnvv** [Saghen/blink.cmp#490] opened 2024-12-10 23:52 UTC
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

In the latest update, when in Insert-Mode, reverting back to previous version Works as a hot fix. 

https://github.com/user-attachments/assets/3735ed29-dcfb-43b8-ac62-49939ce1212a

### neovim version

NVIM v0.10.2

### `blink.cmp` version: branch, tag, or commit

main

**Comment by OmegaLambda1998** [comment] 2024-12-11 00:27
Definitely an issue with the keymap as changing `opts.keymap["<CR>"] = {"accept", "fallback"}` to `opts.keymap["C-CR"] = {"accept", "fallback"}` also fixes it, though obviously changes the keymap used

**Comment by Saghen** [comment] 2024-12-11 00:49
Duplicate of #489

**Closed by Saghen** 2024-12-11 00:49 UTC
Labels: bug
